"""Reproducible typed/voice controller entry point with explicit task boundaries."""

import argparse
import asyncio
import getpass
import json
import signal
import sys
import tomllib
from dataclasses import asdict
from pathlib import Path
from time import time
from uuid import uuid4

from assistant.audio.contracts import Language, Mode, Utterance
from assistant.controller.contracts import Check, Selector, TaskRequest
from assistant.controller.engine import Controller
from assistant.controller.journal import Journal
from assistant.controller.native import Native
from assistant.controller.policy import Grants, Turns
from assistant.controller.preferences import ALLOWED, Preference, Preferences
from assistant.controller.secrets import Credentials
from assistant.controller.state import StateStore
from assistant.controller.voice_session import VoiceSession
from assistant.platform import create_driver
from assistant.platform.base import Target
from assistant.providers.registry import create_models


def parser():
    root = argparse.ArgumentParser(description=__doc__)
    root.add_argument("--config", type=Path, default=Path("config.toml"))
    commands = root.add_subparsers(dest="command", required=True)
    commands.add_parser("doctor")
    commands.add_parser("apps")
    preference = commands.add_parser("preference")
    preference.add_argument("operation", choices=["list", "set"])
    preference.add_argument("key", nargs="?", choices=sorted(ALLOWED))
    preference.add_argument("value", nargs="?")
    preference.add_argument("--scope", default="general")
    key = commands.add_parser("key")
    key.add_argument("provider", choices=["typesafe", "openrouter", "openai", "laya"])
    for name in ("native", "browser", "files"):
        task = commands.add_parser(name)
        task.add_argument("--goal", default="Read the selected original text.")
        task.add_argument("--mode", choices=[m.value for m in Mode], default="read_exact")
        task.add_argument("--language", choices=[v.value for v in Language], default="en")
        task.add_argument("--role", default="text field" if name != "files" else "document")
        task.add_argument(
            "--name", required=True, help="Exact accessible control name or granted relative file"
        )
        task.add_argument(
            "--control", action="append", default=[], help="Additional exact permitted control name"
        )
        task.add_argument("--action", action="append", choices=["set_value", "invoke"], default=[])
        task.add_argument("--preference-scope", default="general")
        task.add_argument("--spoken-language", choices=["en", "yue", "cmn"])
        task.add_argument("--writing-system", choices=["traditional", "simplified"])
        task.add_argument(
            "--value", help="Exact user content; never generated by the routing model"
        )
        task.add_argument(
            "--expect",
            action="append",
            default=[],
            help='Postcondition JSON: {"role":...,"name":...,"value":...}',
        )
        task.add_argument(
            "--allow-cloud",
            action="store_true",
            help=(
                "Allow listed providers/models goal, screen/source text and "
                "preferences for this 5-minute task"
            ),
        )
        task.add_argument(
            "--voice",
            action="store_true",
            help="Explicitly capture one utterance through configured local ASR",
        )
        task.add_argument(
            "--speak", action="store_true", help="Speak results with the configured OS voice"
        )
        task.add_argument(
            "--hotkey",
            action="store_true",
            help="Enable the configured Stop hotkey during this task",
        )
        if name == "native":
            task.add_argument("--pid", required=True, type=int)
            task.add_argument("--window", required=True)
            task.add_argument("--describe", action="store_true")
            task.add_argument(
                "--capture",
                action="store_true",
                help="Grant transient capture of this exact window for description",
            )
        elif name == "browser":
            task.add_argument(
                "--url",
                required=True,
                help="Exact permitted URL, including its trailing slash if any",
            )
            task.add_argument("--headless", action="store_true")
        else:
            task.add_argument(
                "--root",
                required=True,
                type=Path,
                help="Granted absolute folder; Windows backend is not yet qualified",
            )
    return root


async def capture_one(session, turn, config):
    from assistant.audio.devices import microphone_frames
    from assistant.audio.vad import Segmenter, SileroProbability, VADConfig

    vad = VADConfig(
        **{
            key: config["audio"][key]
            for key in (
                "sample_rate",
                "frame_samples",
                "silence_ms",
                "minimum_speech_ms",
                "maximum_utterance_seconds",
            )
        }
    )
    detector = Segmenter(SileroProbability(), vad)
    await session.begin_listening()
    try:
        async for frame in microphone_frames():
            clip = detector.push(frame)
            if clip:
                # Resume the output gate before C can submit a result, avoiding an
                # A/C deadlock while the caller awaits the committed instruction.
                session.finish_listening()
                await session.transcribe(clip, turn)
                return
    finally:
        session.finish_listening()
        detector.reset()


async def task_run(args, config, credentials, turns, grants, journal, state):
    from contextlib import AsyncExitStack, ExitStack

    with ExitStack() as contexts:
        async with AsyncExitStack() as asynchronous:
            scope = "cli-" + uuid4().hex
            language, mode = Language(args.language), Mode(args.mode)
            turn = turns.begin(language, mode, scope)
            if args.command == "native":
                target = Target(args.pid, args.window)
            elif args.command == "browser":
                target = Target(0, args.url)
            else:
                target = Target(-1, str(args.root.resolve()))
            checks = []
            for item in args.expect:
                check = json.loads(item)
                if set(check) != {"role", "name", "value"}:
                    raise ValueError("Each expected result requires exactly role, name and value.")
                checks.append(Check(target, Selector(check["role"], check["name"]), check["value"]))
            controls = frozenset(
                {args.name, *args.control, *(c.selector.name for c in checks), "url", ""}
            )
            actions = {"observe", "read", *args.action}
            if mode == Mode.DICTATE:
                actions.add("set_value")
            if args.command == "browser":
                actions.add("navigate")
            grant = grants.issue(
                kind=args.command,
                scope=scope,
                expires_at=time() + 300,
                target=target,
                controls=controls,
                actions=frozenset(actions),
            )
            decider, planner, chat = create_models(config, credentials)
            for provider in (decider, chat):
                if provider:
                    asynchronous.push_async_callback(provider.close)
            cloud_ids = []
            if args.allow_cloud:
                fields = {"goal", "screen_text", "source_text", "preferences"}
                if getattr(args, "describe", False) and getattr(args, "capture", False):
                    fields.add("screenshot")
                for provider in (decider, chat):
                    if provider and provider.info.locality == "cloud":
                        print(
                            json.dumps(
                                {
                                    "disclosure": provider.info.provider,
                                    "model": provider.info.model,
                                    "fields": sorted(fields),
                                    "expires_in_seconds": 300,
                                }
                            )
                        )
                        permitted = grants.issue(
                            kind="cloud",
                            scope=scope,
                            expires_at=time() + 300,
                            provider=provider.info.provider,
                            model=provider.info.model,
                            fields=frozenset(fields),
                        )
                        cloud_ids.append(permitted.grant_id)
            request = TaskRequest(
                Utterance(turn, args.goal, "text"),
                scope,
                (target,),
                (grant.grant_id,),
                tuple(checks),
                Selector(args.role, args.name),
                args.value,
                tuple(cloud_ids),
                preferences={
                    key: value
                    for key, value in {
                        "spoken_language": args.spoken_language,
                        "writing_system": args.writing_system,
                    }.items()
                    if value is not None
                },
                preference_scope=args.preference_scope,
            )
            if args.command == "browser":
                from assistant.controller.routes import BrowserExecution
                from assistant.mcp_transport import StdioMCPClient
                from assistant.routes.browser.runtime import BrowserRuntime

                runtime = BrowserRuntime(
                    Path.cwd(), Path(".runtime/browser-profile"), args.headless
                )
                command, arguments, cwd = contexts.enter_context(runtime.launch())
                transport = await asynchronous.enter_async_context(
                    StdioMCPClient(command, arguments, cwd)
                )
                execution = BrowserExecution(transport, turns, grants, journal)
            else:
                if args.command == "files":
                    from assistant.controller.routes import FileDriver

                    def factory():
                        return FileDriver(grant, grants)
                else:
                    factory = create_driver
                execution = Native(factory, turns, grants, journal, kind=args.command)
                asynchronous.push_async_callback(execution.close)
            output = asr = None
            if args.speak:
                from assistant.audio.cli import tts_provider
                from assistant.audio.speech_queue import SpeechQueue

                output = SpeechQueue(tts_provider(config))
                asynchronous.push_async_callback(output.close)
            if args.voice:
                from assistant.audio.cli import asr_settings
                from assistant.providers.asr.registry import create_asr

                asr = create_asr(asr_settings(config))
                status = await asr.availability()
                if not status.available:
                    raise RuntimeError("Configured local ASR is unavailable.")
                if hasattr(asr, "close"):
                    asynchronous.push_async_callback(asr.close)
            controller = Controller(
                turns,
                grants,
                execution,
                Preferences(state),
                decider=decider,
                planner=planner,
                speech=output,
                events=lambda event: print(json.dumps(asdict(event)), file=sys.stderr),
            )
            if hasattr(execution, "stop"):
                controller.register_stop_handler(execution.stop)
            controller.bind_input(request)
            session = VoiceSession(asr, output, controller.on_utterance, controller.on_stop)
            loop = asyncio.get_running_loop()
            old_handler = signal.getsignal(signal.SIGINT)

            def interrupt(*_):
                loop.call_soon_threadsafe(
                    lambda: asyncio.create_task(session.stop(turn, "keyboard"))
                )

            signal.signal(signal.SIGINT, interrupt)
            contexts.callback(signal.signal, signal.SIGINT, old_handler)
            if args.hotkey:
                from assistant.audio.hotkeys import StopHotkey

                hotkey = StopHotkey(lambda: session.stop(turn), config["audio"]["stop_hotkey"])
                hotkey.start()
                contexts.callback(hotkey.close)
            if getattr(args, "describe", False):
                from assistant.controller.vision import ScreenDescription
                from assistant.routes.capture import CaptureTarget

                capture_id = ""
                if args.capture:
                    capture_id = grants.issue(
                        kind="capture", scope=scope, expires_at=time() + 300, target=target
                    ).grant_id
                from dataclasses import replace

                vision = ScreenDescription(execution, turns, grants, chat)

                async def describe(current):
                    return await vision.describe(
                        current, 0, CaptureTarget(target.pid, target.window_id), capture_id
                    )

                controller.screen_description = describe
                controller.bind_input(replace(request, feature="describe_screen"))
            if args.voice:
                await capture_one(session, turn, config)
            else:
                text = args.value if mode == Mode.DICTATE and args.value is not None else args.goal
                await session.commit_typed(text, turn)
            result = controller._last_result
            if result:
                print(
                    json.dumps(
                        {
                            "status": result.status,
                            "kind": result.kind.value,
                            "reason": result.reason,
                            "operation_ids": result.operation_ids,
                        }
                    )
                )
                if result.text:
                    print(result.text)  # ephemeral requested UI output, never saved as task history
                return 0 if result.status in {"verified", "generated", "limited"} else 1
            print("Stopped.")
            return 1


async def run(args):
    credentials = Credentials()
    if args.command == "key":
        credentials.set(args.provider, getpass.getpass("Provider credential (hidden): "))
        print("Credential stored in the OS credential store.")
        return 0
    config = tomllib.loads(args.config.read_text(encoding="utf-8"))
    if args.command == "doctor":
        for role in ("decider", "text_model"):
            selected = config.get(role, {})
            configured = False
            try:
                credentials.get(selected.get("provider", ""))
                configured = True
            except RuntimeError:
                pass
            print(
                json.dumps(
                    {
                        "role": role,
                        "enabled": selected.get("enabled", False),
                        "provider": selected.get("provider"),
                        "model": selected.get("model"),
                        "revision": selected.get("revision"),
                        "credential_configured": configured,
                        "cloud_grants": "required per task; not persisted",
                    }
                )
            )
        return 0
    turns, grants = Turns(), Grants()
    runtime = Path(".runtime")
    runtime.mkdir(exist_ok=True)
    journal = Journal(runtime / "operations.db", credentials.journal_key())
    state = StateStore(runtime / "state.db")
    try:
        if args.command == "preference":
            preferences = Preferences(state)
            if args.operation == "set":
                if args.key is None or args.value is None:
                    raise ValueError("Specify the preference key and value.")
                preferences.accept(Preference(args.key, args.value, args.scope, True))
                print("Accepted preference saved. It grants no app, folder or cloud access.")
            else:
                print(json.dumps(preferences.resolve(args.scope), ensure_ascii=False))
            return 0
        if args.command == "apps":
            native = Native(create_driver, turns, grants, journal)
            try:
                print(
                    json.dumps(
                        await native.call(lambda: asdict(native._get().focused())),
                        ensure_ascii=False,
                    )
                )
                return 0
            finally:
                await native.close()
        return await task_run(args, config, credentials, turns, grants, journal, state)
    finally:
        state.close()
        journal.close()


def main():
    args = parser().parse_args()
    try:
        code = asyncio.run(run(args))
    except KeyboardInterrupt:
        code = 1
        print("Stopped; an in-flight change may still have committed.", file=sys.stderr)
    except Exception:
        code = 1
        print(
            "Controller unavailable: check configuration, permissions and selected route.",
            file=sys.stderr,
        )
    raise SystemExit(code)
